package bmosim.exchange.dialog;

public enum Queries {
OFFER_DATA_REQUEST,
OFFER_DATA,

SAVE_CUSTOMER_DATA,
CUSTOMER_DATA_REQUEST,
CUSTOMER_DATA,

OBJECT_DATA_REQUEST,
OBJECT_DATA,

OFFERS_REQUEST,
AVAILABLE_OFFERS,
ALTERNATIVE_OFFER_DATA_REQUEST,
ALTERNATIVE_OFFER_DATA,

SAVE_ORDER,
ORDER_DATA,
ORDERS_DATA,
ORDER_INFO,


ORDER_STATE_AWAITING_DELIVERY,
ORDER_STATE_IN_DELIVERY,
ORDER_STATE_DELIVERED,
ORDER_STATE_CANCELLED,

SAVE_FEEDBACK,

// manager queries
SAVE_TYPE,
SAVE_PRODUCT,
SAVE_OFFER,				//OK
SET_HIGHLIGHTED_OFFER,

// DB queries


GET_CUSTOMER,
GET_CUSTOMERS,/*brahim*/
CUSTOMER_INFO,
CUSTOMERS_INFO,/*brahim*/
GET_CUSTOMER_NEEDS,/*brahim*/
GET_CUSTOMER_ORDERS,/*brahim*/
GET_CUSTOMER_OFFER,/*brahim*/
GET_CUSTOMER_PRODUCT,/*brahim*/
GET_DEL_ORDER,
DELIVERY_VOUCHER,

SET_ORDER_STATUS,
UPDATE_ORDER_DELIVERY,
UPDATE_ORDER_TO_DELIVERING,
UPDATE_ORDER_TO_DELIVERED,
UPDATE_ORDER_TO_CANCELLED,

GET_NEED,
GET_CHANNEL,
GET_OFFER,
GET_ORDER,
GET_PRODUCT,
GET_TYPE,
GET_HIGHLIGHTED_OFFER,

PRODUCT_DATA,


}
