package bmosim.bmo;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: RevenueStream <br>
 * @version generated on Thu Oct 26 02:05:01 WAT 2017 by Hichem
 */

public interface RevenueStream extends BMElement {

    /* ***************************************************
     * Property http://www.owl-ontologies.com/unnamed.owl#pricingMethod
     */
     
    /**
     * Gets all property values for the pricingMethod property.<p>
     * 
     * @returns a collection of values for the pricingMethod property.
     */
    Collection<? extends Object> getPricingMethod();

    /**
     * Checks if the class has a pricingMethod property value.<p>
     * 
     * @return true if there is a pricingMethod property value.
     */
    boolean hasPricingMethod();

    /**
     * Adds a pricingMethod property value.<p>
     * 
     * @param newPricingMethod the pricingMethod property value to be added
     */
    void addPricingMethod(Object newPricingMethod);

    /**
     * Removes a pricingMethod property value.<p>
     * 
     * @param oldPricingMethod the pricingMethod property value to be removed.
     */
    void removePricingMethod(Object oldPricingMethod);



    /* ***************************************************
     * Property http://www.owl-ontologies.com/unnamed.owl#reasoning
     */
     
    /**
     * Gets all property values for the reasoning property.<p>
     * 
     * @returns a collection of values for the reasoning property.
     */
    Collection<? extends String> getReasoning();

    /**
     * Checks if the class has a reasoning property value.<p>
     * 
     * @return true if there is a reasoning property value.
     */
    boolean hasReasoning();

    /**
     * Adds a reasoning property value.<p>
     * 
     * @param newReasoning the reasoning property value to be added
     */
    void addReasoning(String newReasoning);

    /**
     * Removes a reasoning property value.<p>
     * 
     * @param oldReasoning the reasoning property value to be removed.
     */
    void removeReasoning(String oldReasoning);



    /* ***************************************************
     * Property http://www.owl-ontologies.com/unnamed.owl#revenueCategory
     */
     
    /**
     * Gets all property values for the revenueCategory property.<p>
     * 
     * @returns a collection of values for the revenueCategory property.
     */
    Collection<? extends Object> getRevenueCategory();

    /**
     * Checks if the class has a revenueCategory property value.<p>
     * 
     * @return true if there is a revenueCategory property value.
     */
    boolean hasRevenueCategory();

    /**
     * Adds a revenueCategory property value.<p>
     * 
     * @param newRevenueCategory the revenueCategory property value to be added
     */
    void addRevenueCategory(Object newRevenueCategory);

    /**
     * Removes a revenueCategory property value.<p>
     * 
     * @param oldRevenueCategory the revenueCategory property value to be removed.
     */
    void removeRevenueCategory(Object oldRevenueCategory);



    /* ***************************************************
     * Property http://www.owl-ontologies.com/unnamed.owl#synonyms
     */
     
    /**
     * Gets all property values for the synonyms property.<p>
     * 
     * @returns a collection of values for the synonyms property.
     */
    Collection<? extends String> getSynonyms();

    /**
     * Checks if the class has a synonyms property value.<p>
     * 
     * @return true if there is a synonyms property value.
     */
    boolean hasSynonyms();

    /**
     * Adds a synonyms property value.<p>
     * 
     * @param newSynonyms the synonyms property value to be added
     */
    void addSynonyms(String newSynonyms);

    /**
     * Removes a synonyms property value.<p>
     * 
     * @param oldSynonyms the synonyms property value to be removed.
     */
    void removeSynonyms(String oldSynonyms);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
