package bmosim.bmo;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Thu Oct 26 02:05:01 WAT 2017 by Hichem
 */

public class Vocabulary {

//	//private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#Activity
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class ACTIVITY.<p>
//     *
//     */
////    public static final OWLClass CLASS_ACTIVITY = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#Activity"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#Actor
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class ACTOR.<p>
//     *
//     */
//    public static final OWLClass CLASS_ACTOR = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#Actor"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#BMElement
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class BMELEMENT.<p>
//     *
//     */
//    public static final OWLClass CLASS_BMELEMENT = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#BMElement"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#CoreCapability
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class CORECAPABILITY.<p>
//     *
//     */
//    public static final OWLClass CLASS_CORECAPABILITY = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#CoreCapability"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#CostAccount
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class COSTACCOUNT.<p>
//     *
//     */
//    public static final OWLClass CLASS_COSTACCOUNT = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#CostAccount"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#CustomerSegment
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class CUSTOMERSEGMENT.<p>
//     *
//     */
//    public static final OWLClass CLASS_CUSTOMERSEGMENT = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#CustomerSegment"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#DistributionChannel
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class DISTRIBUTIONCHANNEL.<p>
//     *
//     */
//    public static final OWLClass CLASS_DISTRIBUTIONCHANNEL = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#DistributionChannel"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#DistributionLink
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class DISTRIBUTIONLINK.<p>
//     *
//     */
//    public static final OWLClass CLASS_DISTRIBUTIONLINK = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#DistributionLink"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#PartnershipAgreement
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class PARTNERSHIPAGREEMENT.<p>
//     *
//     */
//    public static final OWLClass CLASS_PARTNERSHIPAGREEMENT = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#PartnershipAgreement"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#RelationshipMechanism
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class RELATIONSHIPMECHANISM.<p>
//     *
//     */
//    public static final OWLClass CLASS_RELATIONSHIPMECHANISM = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#RelationshipMechanism"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#Resource
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class RESOURCE.<p>
//     *
//     */
//    public static final OWLClass CLASS_RESOURCE = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#Resource"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#RevenueStream
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class REVENUESTREAM.<p>
//     *
//     */
//    public static final OWLClass CLASS_REVENUESTREAM = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#RevenueStream"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#ValueChain
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class VALUECHAIN.<p>
//     *
//     */
//    public static final OWLClass CLASS_VALUECHAIN = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#ValueChain"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#ValueChainActivity
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class VALUECHAINACTIVITY.<p>
//     *
//     */
//    public static final OWLClass CLASS_VALUECHAINACTIVITY = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#ValueChainActivity"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#ValueConfiguration
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class VALUECONFIGURATION.<p>
//     *
//     */
//    public static final OWLClass CLASS_VALUECONFIGURATION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#ValueConfiguration"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#ValueNetwork
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class VALUENETWORK.<p>
//     *
//     */
//    public static final OWLClass CLASS_VALUENETWORK = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#ValueNetwork"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#ValueNetworkActivity
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class VALUENETWORKACTIVITY.<p>
//     *
//     */
//    public static final OWLClass CLASS_VALUENETWORKACTIVITY = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#ValueNetworkActivity"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#ValueProposition
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class VALUEPROPOSITION.<p>
//     *
//     */
//    public static final OWLClass CLASS_VALUEPROPOSITION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#ValueProposition"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#ValueShop
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class VALUESHOP.<p>
//     *
//     */
//    public static final OWLClass CLASS_VALUESHOP = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#ValueShop"));
//
//    /* ***************************************************
//     * Class http://www.owl-ontologies.com/unnamed.owl#ValueShopActivity
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL api representation of the class VALUESHOPACTIVITY.<p>
//     *
//     */
//    public static final OWLClass CLASS_VALUESHOPACTIVITY = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/unnamed.owl#ValueShopActivity"));
//
//    /* ***************************************************
//     * Object Property http://protege.stanford.edu/plugins/owl/protege#FROM
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property FROM.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_FROM = factory.getOWLObjectProperty(IRI.create("http://protege.stanford.edu/plugins/owl/protege#FROM"));
//
//    /* ***************************************************
//     * Object Property http://protege.stanford.edu/plugins/owl/protege#TO
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property TO.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_TO = factory.getOWLObjectProperty(IRI.create("http://protege.stanford.edu/plugins/owl/protege#TO"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#concerns
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property CONCERNS.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_CONCERNS = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#concerns"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#correspondsTo
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property CORRESPONDSTO.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_CORRESPONDSTO = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#correspondsTo"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#creates
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property CREATES.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_CREATES = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#creates"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#delivers
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property DELIVERS.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_DELIVERS = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#delivers"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#implements
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property IMPLEMENTS.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_IMPLEMENTS = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#implements"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#isConcernedBy
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property ISCONCERNEDBY.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONCERNEDBY = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#isConcernedBy"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#isCreatedBy
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property ISCREATEDBY.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_ISCREATEDBY = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#isCreatedBy"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#isDeliveredBy
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property ISDELIVEREDBY.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_ISDELIVEREDBY = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#isDeliveredBy"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#isImplementedBy
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property ISIMPLEMENTEDBY.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_ISIMPLEMENTEDBY = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#isImplementedBy"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#isNeededBy
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property ISNEEDEDBY.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_ISNEEDEDBY = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#isNeededBy"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#isPrecededBy
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property ISPRECEDEDBY.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_ISPRECEDEDBY = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#isPrecededBy"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#isRefinedBy
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property ISREFINEDBY.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_ISREFINEDBY = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#isRefinedBy"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#isRelatedVia
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property ISRELATEDVIA.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_ISRELATEDVIA = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#isRelatedVia"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#isRequiredBy
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property ISREQUIREDBY.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_ISREQUIREDBY = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#isRequiredBy"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#isServedBy
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property ISSERVEDBY.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_ISSERVEDBY = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#isServedBy"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#isTargetedBy
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property ISTARGETEDBY.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_ISTARGETEDBY = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#isTargetedBy"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#needs
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property NEEDS.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_NEEDS = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#needs"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#precedes
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property PRECEDES.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_PRECEDES = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#precedes"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#refines
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property REFINES.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_REFINES = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#refines"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#relates
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property RELATES.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_RELATES = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#relates"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#requires
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property REQUIRES.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_REQUIRES = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#requires"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#serves
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property SERVES.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_SERVES = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#serves"));
//
//    /* ***************************************************
//     * Object Property http://www.owl-ontologies.com/unnamed.owl#targets
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the object property TARGETS.<p>
//     *
//     */
//    public static final OWLObjectProperty OBJECT_PROPERTY_TARGETS = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#targets"));
//
//    /* ***************************************************
//     * Data Property http://protege.stanford.edu/plugins/owl/protege#PAL-DESCRIPTION
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property PAL_DESCRIPTION.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_PAL_DESCRIPTION = factory.getOWLDataProperty(IRI.create("http://protege.stanford.edu/plugins/owl/protege#PAL-DESCRIPTION"));
//
//    /* ***************************************************
//     * Data Property http://protege.stanford.edu/plugins/owl/protege#PAL-NAME
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property PAL_NAME.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_PAL_NAME = factory.getOWLDataProperty(IRI.create("http://protege.stanford.edu/plugins/owl/protege#PAL-NAME"));
//
//    /* ***************************************************
//     * Data Property http://protege.stanford.edu/plugins/owl/protege#PAL-RANGE
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property PAL_RANGE.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_PAL_RANGE = factory.getOWLDataProperty(IRI.create("http://protege.stanford.edu/plugins/owl/protege#PAL-RANGE"));
//
//    /* ***************************************************
//     * Data Property http://protege.stanford.edu/plugins/owl/protege#PAL-STATEMENT
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property PAL_STATEMENT.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_PAL_STATEMENT = factory.getOWLDataProperty(IRI.create("http://protege.stanford.edu/plugins/owl/protege#PAL-STATEMENT"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#ActivityLevel
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property ACTIVITYLEVEL.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_ACTIVITYLEVEL = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#ActivityLevel"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#CostAccountCategory
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property COSTACCOUNTCATEGORY.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_COSTACCOUNTCATEGORY = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#CostAccountCategory"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#Percentage
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property PERCENTAGE.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_PERCENTAGE = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#Percentage"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#channelCategory
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property CHANNELCATEGORY.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_CHANNELCATEGORY = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#channelCategory"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#competitionDegree
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property COMPETITIONDEGREE.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_COMPETITIONDEGREE = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#competitionDegree"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#competitionDegreeComments
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property COMPETITIONDEGREECOMMENTS.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_COMPETITIONDEGREECOMMENTS = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#competitionDegreeComments"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#criterion
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property CRITERION.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_CRITERION = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#criterion"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#customerBuyingCycle
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property CUSTOMERBUYINGCYCLE.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_CUSTOMERBUYINGCYCLE = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#customerBuyingCycle"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#customerEquity
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property CUSTOMEREQUITY.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_CUSTOMEREQUITY = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#customerEquity"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#integrationDegree
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property INTEGRATIONDEGREE.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_INTEGRATIONDEGREE = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#integrationDegree"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#integrationDegreeComments
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property INTEGRATIONDEGREECOMMENTS.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_INTEGRATIONDEGREECOMMENTS = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#integrationDegreeComments"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#lifeCycle
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property LIFECYCLE.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_LIFECYCLE = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#lifeCycle"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#lifeCycleComments
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property LIFECYCLECOMMENTS.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_LIFECYCLECOMMENTS = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#lifeCycleComments"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#partnershipCategory
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property PARTNERSHIPCATEGORY.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_PARTNERSHIPCATEGORY = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#partnershipCategory"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#priceLevel
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property PRICELEVEL.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_PRICELEVEL = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#priceLevel"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#priceLevelComments
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property PRICELEVELCOMMENTS.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_PRICELEVELCOMMENTS = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#priceLevelComments"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#pricingMethod
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property PRICINGMETHOD.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_PRICINGMETHOD = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#pricingMethod"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#reasoning
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property REASONING.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_REASONING = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#reasoning"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#resourceCategory
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property RESOURCECATEGORY.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_RESOURCECATEGORY = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#resourceCategory"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#revenueCategory
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property REVENUECATEGORY.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_REVENUECATEGORY = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#revenueCategory"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#strategicImportance
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property STRATEGICIMPORTANCE.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_STRATEGICIMPORTANCE = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#strategicImportance"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#strategicImportanceComments
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property STRATEGICIMPORTANCECOMMENTS.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_STRATEGICIMPORTANCECOMMENTS = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#strategicImportanceComments"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#switchingCost
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property SWITCHINGCOST.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_SWITCHINGCOST = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#switchingCost"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#switchingCostComments
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property SWITCHINGCOSTCOMMENTS.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_SWITCHINGCOSTCOMMENTS = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#switchingCostComments"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#synonyms
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property SYNONYMS.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_SYNONYMS = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#synonyms"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#valueChainActivityNature
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property VALUECHAINACTIVITYNATURE.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_VALUECHAINACTIVITYNATURE = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#valueChainActivityNature"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#valueLevel
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property VALUELEVEL.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_VALUELEVEL = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#valueLevel"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#valueLevelComments
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property VALUELEVELCOMMENTS.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_VALUELEVELCOMMENTS = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#valueLevelComments"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#valueNetworkActivityNature
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property VALUENETWORKACTIVITYNATURE.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_VALUENETWORKACTIVITYNATURE = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#valueNetworkActivityNature"));
//
//    /* ***************************************************
//     * Data Property http://www.owl-ontologies.com/unnamed.owl#valueShopActivityNature
//     */
//
//    /**
//     * A constant to give access to the Manchester OWL API representation of the data property VALUESHOPACTIVITYNATURE.<p>
//     *
//     */
//    public static final OWLDataProperty DATA_PROPERTY_VALUESHOPACTIVITYNATURE = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/unnamed.owl#valueShopActivityNature"));


}
